### ISSUE TITLE
beta synchronization secrets endpoints are missing

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#127]
[this endpoint](https://docs.microsoft.com/en-us/graph/api/synchronization-synchronization-secrets?view=graph-rest-beta&tabs=http) is missing from our OpenAPI description because we're missing an operation restriction annotation on the complex type property

**Comment by baywet** [comment]
Closing as the metadata has been updated

**Comment by tagur87** [comment]
Hello! Not sure if this is the best place to report this, but thought I'd give it a shot. 

We have noticed an issue with the `https://graph.microsoft.com/beta/servicePrincipals/${serviceprincipal}/synchronization/secrets` api endpoint. 


It only supports GET and PUT, so if you want to remove secrets, you have to perform a PUT with the value of the secret as `""`. 

However, this only works if the original `value` of the secret was a plain string value.
If the value was a complex type, such as a JSON blob (as in the example here: https://learn.microsoft.com/en-us/graph/api/synchronization-synchronization-secrets?view=graph-rest-beta&tabs=http#request), there does not appear to be a way to remove the secret because if you set the value to an empty `""` string, you get the following error:
```
Bad Request({"error":{"code":"UnknownError","message":"{\r\n  \"error\":{\r\n    \"code\":\"InvalidNotificationSettings\",\"message\":null,\"target\":null,\"details\":[\r\n      \r\n    ],\"innerError\":null\r\n  }\r\n}","innerError":{"date":"2023-01-11T16:57:55","request-id":"8927006e-edb2-435b-a966-49559c4fd064","client-request-id":"8927006e-edb2-435b-a966-49559c4fd064"}}})
```

We also tried setting the value to `"{}"`, which worked, but leaves the secret in place like below:
```json
{
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#servicePrincipals('123456-12312312-123123-')/synchronization/secrets",
  "value": [
    {
      "key": "SyncNotificationSettings",
      "value": "{}"
    }
  ]
}
```

Is this an API bug?

**Comment by tagur87** [comment]
@irvinesunday, is the bug I reported above fixed it this as well?
