### ISSUE TITLE
Consider setting AddAlternateKeyPaths to true in the conversion settings

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#305]
APIs such as [List members of a directory role](https://learn.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0) now support [alternate keys](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_AlternateKeys):
``` http
GET /directoryRoles/{role-id}/members
GET /directoryRoles(roleTemplateId='{roleTemplateId}')/members
```

We should consider setting `AddAlternateKeyPaths` to `true` in the CSDL to OpenAPI conversion settings at https://github.com/microsoftgraph/msgraph-metadata/tree/master/conversion-settings to support the alternate key in our SDKs.

As part of this change, we should monitor the net effect of this setting on the growth of the number of paths.

**Comment by irvinesunday** [comment]
I will do a path count diff of the two files with the setting `true` and `false` and share the results here.

**Comment by darrelmiller** [comment]
/cc @baywet Does Kiota currently handle this kind of alternate path syntax?

@irvinesunday  I think this issue should be transferred over to the OpenAPI.OData  repo.

**Comment by baywet** [comment]
@darrelmiller yes, you'll get a directoryRolesByRoleTemplateId method in the fluent API surface.
Since we [already have the setting in the conversion lib](https://github.com/microsoft/OpenAPI.NET.OData/blob/8fcb0461050d21d5b133a97a5c454f94c5723296/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L155) is merely a matter of updating the configuration files here, no action is needed in the conversion lib unless I missed something. So I'd argue against moving this issue.

**Comment by njaci1** [comment]
@irvinesunday how did this go?

**Comment by irvinesunday** [comment]
Setting `AddAlternateKeyPaths` increases the paths for v1.0 from 6237 - 6241 paths. This is quite an insignificant increase.
