### ISSUE TITLE
DELETE `/directory/deletedItems/{directoryObject-id}` is missing in beta metadata but present in v1

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-metadata#566]
Reference doc at https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-delete?view=graph-rest-beta&tabs=http

Sourced from https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/792

The path `/directory/deletedItems/{directoryObject-id}` should have DELETE method in beta openApi file

**Comment by irvinesunday** [comment]
In hindsight, we really shouldn't even be generating `delete` operation in `v1.0`. This is because non-containment navigation properties should not have a `delete` operation unless the deletability has been explicitly set via the annotation. The reason we currently generate delete operation in `v1.0` is because of a bug in the conversion lib. where we check the `IsDeletable` property (which will default to `true` if  `Deletable` is `null`) instead of using the `Deletable` property:

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/8354a444-cfb9-4b12-baf1-6379bf6a0a8a)

We don't generate the same for `beta` because of a casing mismatch in the nav. prop name: 
![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/b30dd858-47d8-49c2-82b2-8447f026070c)
Notice the small casing: `deleteditems` instead of `deletedItems`

Here's the similar annotation in v1.0
![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/51ec31f6-5105-4310-b15d-82baa3495bc8)

@millicentachieng are you able to track down with ApiDoctor why the same annotation gets injected into the different versions of the metadata with varying casings?

@andrueastman to fix this issue:
1. We need to wholesomely fix the bug in the conversion lib. Already tracked in the [issue](https://github.com/microsoft/OpenAPI.NET.OData/issues/483): 
2. Update XSL to add the `deletability` property to the `DeleteRestrictions` annotation

**Comment by millicentachieng** [comment]
@irvinesunday It depends on how the examples have been documented. Inconsistencies within the documentation will be reflected in the metadata too.

For example, in the case you've highlighted, see the corresponding examples in the docs:

<img width="530" alt="image" src="https://github.com/microsoftgraph/msgraph-metadata/assets/25274795/9c46bfa4-be09-4f36-bb5d-36f72754e726">

<img width="520" alt="image" src="https://github.com/microsoftgraph/msgraph-metadata/assets/25274795/8db40a6f-b782-4b33-9804-29e439dce1c8">
