### ISSUE TITLE
Duplicate "accept" action in v1.0 metadata breaks DevX API

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#59]
Getting the latest v1.0 OpenAPI document from DevX API results in a duplicate key error for accept action.
Repro steps:
- Get the latest v1.0 OpenAPI document from DevX API - https://graphexplorerapi.azurewebsites.net/openapi/operations?openapiversion=3&style=Powershell&graphVersion=v1.0&forcerefresh=true.
- `"An item with the same key has already been added. Key: /groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept"` error is retuned.

It looks like this change is coming from our XSLT transform step which adds an additional `accept` action that is bound to an `event`.

This is currently blocking the release of PR https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/519.
Related to https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/432.

\cc @MIchaelMainer, @zengin  
[AB#7828](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7828)

**Comment by MIchaelMainer** [comment]
Caused by https://github.com/microsoftgraph/msgraph-metadata/pull/53.

We'll need to revert that change in the XSLT.  Action overload does not include changes to the parameter order so this change wasn't OData compliant ([action overload resolution](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31359015). 

@zengin I don't think we can maintain both. Could we make a change in the docs to help with this scenario?

**Comment by zengin** [comment]
Interesting limitation from OData. I am looking at how we can address this. We can't fix it in the docs as we need the parameter that we are adding. The backwards compatible version is there only because we don't want to break code. It misses the intended functionality.

**Comment by zengin** [comment]
Meanwhile I think I can just revert the latest change. @MIchaelMainer did we generate any SDKs using this version of the XSLT?

**Comment by MIchaelMainer** [comment]
No, because we have a bug in the generation pipeline. I'm looking at that now.
